name: PJCS
favicon: null
layout_spectrum: 1
typography_spectrum: 0.66488
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#9c9d9c'
    - '#6a6b6d'
    - '#c5112e'
    - '#a33f6b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
